95 track app version
rendayigit/SpaceLoader pull request #103
Opened 2022-10-18 11:17 UTC by mrtkrkrt

2022-10-29 14:16 UTC, rendayigit requested changes

2022-10-29 14:16 UTC, rendayigit commented on .github/workflows/ci.yml
> +        echo "Some text here." > VERSION
Are these changes still necessary?

2022-10-31 12:40 UTC, rendayigit requested changes

2022-10-31 12:40 UTC, rendayigit commented on .github/workflows/version.yaml
> +          majorversion+=$updatedminorversion
```suggestion
          updatedfullversion = $majorversion + $dot + $updatedminorversion
```

2022-10-31 12:40 UTC, rendayigit commented on .github/workflows/version.yaml
> +          versionmessage="Updated Version File. New Version is $majorversion"
```suggestion
          versionmessage="Updated Version File. New Version is $updatedfullversion"
```

2022-10-31 12:40 UTC, rendayigit commented on .github/workflows/version.yaml
> +          echo $majorversion | tee VERSION
```suggestion
          echo $updatedfullversion | tee VERSION
```

2022-10-31 12:40 UTC, rendayigit commented on .github/workflows/version.yaml
> +          git add .
```suggestion
          git add bin/Version
```

2022-10-31 12:57 UTC, mrtkrkrt commented on .github/workflows/ci.yml
> +        echo "Some text here." > VERSION
done

2022-10-31 12:57 UTC, mrtkrkrt commented on .github/workflows/version.yaml
> +          majorversion+=$updatedminorversion
done

2022-10-31 12:58 UTC, mrtkrkrt commented on .github/workflows/version.yaml
> +          versionmessage="Updated Version File. New Version is $majorversion"
done

2022-10-31 12:58 UTC, mrtkrkrt commented on .github/workflows/version.yaml
> +          echo $majorversion | tee VERSION
done

2022-10-31 12:58 UTC, mrtkrkrt commented on .github/workflows/version.yaml
> +          git add .
done

2022-10-31 14:37 UTC, rendayigit requested changes

2022-10-31 14:37 UTC, rendayigit commented on .github/workflows/version.yaml
> +          echo $updatedFullVersion | tee VERSION
is this line necessary?

2022-10-31 14:37 UTC, rendayigit commented on .github/workflows/version.yaml
> +          updatedFullVersion=$majorVersion$dot$updatedMinorVersion
what happens if we add spaces between the variables on right? will it break the code?

2022-10-31 14:37 UTC, rendayigit commented on .github/workflows/version.yaml
> +          updatedFullVersion=$majorVersion$dot$updatedMinorVersion
Also does work when we do `$majorVersion "." $updatedMinorVersion`? Its ugly to do dot="."

2022-11-01 05:09 UTC, mrtkrkrt commented on .github/workflows/version.yaml
> +          updatedFullVersion=$majorVersion$dot$updatedMinorVersion
yes if we add space code gives us error.

> what happens if we add spaces between the variables on right? will it break the code?



 Also does it work when we do `$majorVersion "." $updatedMinorVersion`? Its ugly to do `dot="."`
> I will try and get back to you right away

2022-11-01 05:09 UTC, mrtkrkrt commented on .github/workflows/version.yaml
> +          echo $updatedFullVersion | tee VERSION
all of them?

2022-11-01 05:11 UTC, mrtkrkrt commented on .github/workflows/version.yaml
> +          updatedFullVersion=$majorVersion$dot$updatedMinorVersion
> Also does it work when we do `$majorVersion "." $updatedMinorVersion`? Its ugly to do `dot="."`
It can. Fİxed

2022-11-01 11:25 UTC, rendayigit requested changes

2022-11-01 11:25 UTC, rendayigit commented on .github/workflows/version.yml
> +            updatedFullVersion = lines[3].split(" = ")[1].split(".")[0] + "."  + str(int(lines[3].split(" = ")[1].split(".")[1]) + 1) # handle ;
Delete `# handle ;` please

2022-11-01 12:21 UTC, mrtkrkrt commented on .github/workflows/version.yml
> +            updatedFullVersion = lines[3].split(" = ")[1].split(".")[0] + "."  + str(int(lines[3].split(" = ")[1].split(".")[1]) + 1) # handle ;
fixed

2022-11-01 12:42 UTC, merged