edit yaml funcs
rendayigit/SpaceLoader pull request #19
Opened 2022-03-07 11:18 UTC by mrtkrkrt

Test will arrange.

2022-03-07 15:42 UTC, rendayigit requested changes
My main request is for all these changes are to rename the ones that are named "multiple" to "Vector". (Like "getMultipleNodeByTag" to "getNodeVectorByTag"). And rename the ones that are "Single" to their previous names. (Like "getSingleText" to "getText"). Also please revert unrelated files like the files under .vscode dir. We may change them in a separate branch if necessary.

2022-03-07 15:42 UTC, rendayigit commented on .vscode/cmake-kits.json
> +          "CXX": "/usr/bin/g++-8"
This is not related to the current issue. Please revert this.

2022-03-07 15:42 UTC, rendayigit commented on common.h
> +const QString paths_Yaml = "/home/pc/Desktop/SpaceLoader/Setup/Paths.yaml";
Please revert this line.

2022-03-07 15:42 UTC, rendayigit commented on lib/YAML/yaml.cpp
> +T Yaml::getMultipleNodeByTag(const string &yamlFilePath, const string &tagName,
`getNodeVectorByTag` would be a better name.

2022-03-07 15:42 UTC, rendayigit commented on lib/YAML/yaml.cpp
> +T Yaml::getSingleNodeByTag(const string &yamlFilePath, const string &tagName) {
`getNodeByTag` is better.

2022-03-07 15:42 UTC, rendayigit commented on lib/YAML/yaml.cpp
> +T Yaml::getMultipleNodeByTag(const string &yamlFilePath, const string &tagName) {
`getNodeVectorByTag`  is better.

2022-03-07 15:42 UTC, rendayigit commented on lib/YAML/yaml.cpp
> +T Yaml::getSingleText(const YAML::Node &node, const string &tagName) {
We should go with `getText`.

2022-03-07 15:42 UTC, rendayigit commented on lib/YAML/yaml.cpp
> +T Yaml::getSingleText(const std::string &yamlFilePath, const std::string &tagName) {
`getText` is better.

2022-03-07 15:42 UTC, rendayigit commented on lib/YAML/yaml.cpp
> +T Yaml::getSingleNodeByPath(const string &yamlFilePath, const string &path) {
`getNodeByPath` is better.

2022-03-08 07:38 UTC, rendayigit requested changes
Rename "Vectors" to "Lists". So it becomes "getNodeList" instead of "getNodeVector".
Also "getVectorText" is not right. "getTextList" is better.
And merge main to this branch.

2022-03-08 08:12 UTC, mrtkrkrt commented
> Rename "Vectors" to "Lists". So it becomes "getNodeList" instead of "getNodeVector". Also "getVectorText" is not right. "getTextList" is better. And merge main to this branch.

Done.

2022-03-08 08:29 UTC, rendayigit requested changes

2022-03-08 08:29 UTC, rendayigit commented on lib/YAML/yaml.h
> +    static T getNodeListByPath(const std::string &yamlFilePath, const std::string &path);
Also add getNodeByPath

2022-03-08 12:47 UTC, mrtkrkrt commented on lib/YAML/yaml.h
> +    static T getNodeListByPath(const std::string &yamlFilePath, const std::string &path);
We have already defined the "getNodeByTag" function above the specified field. :)

2022-03-21 19:23 UTC, rendayigit requested changes

2022-03-21 19:23 UTC, rendayigit commented on tests/TCP/test_tcp.cpp
>  #include <QtConcurrent/QtConcurrent>
Move these changes to a different branch if they are important.

2022-03-21 19:23 UTC, rendayigit commented on tests/CMakeLists.txt
>  find_package(Qt5Widgets REQUIRED)
Ucomment the tests so we can merge to main.

2022-03-22 07:22 UTC, mrtkrkrt commented on tests/TCP/test_tcp.cpp
>  #include <QtConcurrent/QtConcurrent>
Done.

2022-03-22 07:25 UTC, mrtkrkrt commented on tests/CMakeLists.txt
>  find_package(Qt5Widgets REQUIRED)
Uncommented tests. For Now, only ThreadSafety test is not working.

2022-03-22 08:44 UTC, mrtkrkrt commented
> Rename "Vectors" to "Lists". So it becomes "getNodeList" instead of "getNodeVector". Also "getVectorText" is not right. "getTextList" is better. And merge main to this branch.

Done

2022-03-22 11:19 UTC, rendayigit approved these changes

2022-03-22 11:21 UTC, merged